#include "GroveMiniTrackBall.h"
#include "../HAL/HalSystem.h"

enum MOTION_REG_ADDR
{
	MOTION_REG_UP = 0x00,
	MOTION_REG_DOWN,
	MOTION_REG_LEFT,
	MOTION_REG_RIGHT,
	MOTION_REG_CONFIRM,
	MOTION_REG_NUM
};

enum CONFIG_REG_ADDR
{
	CONFIG_REG_VALID = MOTION_REG_NUM,
	CONFIG_REG_I2C_ADDR = CONFIG_REG_VALID + 4,
	CONFIG_REG_I2C_SPEED,
	CONFIG_REG_LED_MODE = CONFIG_REG_I2C_SPEED + 2,
	CONFIG_REG_LED_FLASH_TIME,
	CONFIG_REG_DATA_CLEAR_TIME = CONFIG_REG_LED_FLASH_TIME + 2,  //CONFIG_REG_LED_FLASH_TIME has 2bytes
	CONFIG_REG_DATA_READ_TIME = CONFIG_REG_DATA_CLEAR_TIME + 2,
	CONFIG_REG_NUM = CONFIG_REG_DATA_READ_TIME + 2
};

enum LED_MODE
{
	LED_FLASH_1 = 0x00,
	LED_FLASH_2,
	LED_FLASH_TOGGLE,
	LED_FLASH_ALL,
	LED_ALWAYS_ON_1,
	LED_ALWAYS_ON_2,
	LED_ALWAYS_ON_ALL,
	LED_ALWAYS_OFF,
	LED_BREATHING_1,
	LED_BREATHING_2,
	LED_BREATHING_ALL,
	LED_MOVE_FLASH,
	LED_MODE_NUM
};

void GroveMiniTrackBall::SetLedMode(uint8_t ledMode)
{
	_Device->WriteRegByte(CONFIG_REG_LED_MODE, ledMode);
}

void GroveMiniTrackBall::Init()
{
}

void GroveMiniTrackBall::Read()
{
	for (uint8_t i = 0; i < (uint8_t)LED_MODE_NUM; i++)
	{
		SetLedMode(i);
		HalSystem::DelayMs(5000);
	}
}
